title: Bgc
description: >-
  Bidding Game Challenge. Create your own agent for our round-based bidding game and compete against others!
url: https://roehrt.github.io
baseurl: /bgc
markdown: redcarpet
highlighter: pygments
version: 0.1
repo: https://github.com/roehrt/bcg