title: Bgc
description: >-
  Bidding Game Challenge. Write an agent that plays a bidding game.
url: https://roehrt.github.io
baseurl: /bgc
markdown: redcarpet
highlighter: pygments
version: 0.1
repo: https://github.com/roehrt/bcg